# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

ingredients_list = [
"abalone",
"achar",
"acidulated water",
"ackee",
"acorn squash",
"adobo",
"advieh",
"African birdseye chile peppers",
"agar",
"aioli",
"Ajowan",
"ale",
"aleppo pepper",
"alfalfa sprouts",
"alfredo sauce",
"alize liqueur",
"alligator",
"allspice",
"almonds",
"Almond Bark",
"almond butter",
"almond extract",
"almond paste",
"amaranth",
"amarena cherries",
"amaretti",
"amaretto",
"amarula cream liqueur",
"amchoor powder",
"amla",
"ancho chile peppers",
"anchovette",
"anchovies",
"anchovy paste",
"andouille sausage",
"angelica",
"anise",
"annatto seeds",
"apples",
"apple butter",
"apple pie spice",
"applesauce",
"apricots",
"aquavit",
"arak",
"arborio rice",
"argan oil",
"arrowroot",
"artichokes",
"artificial sweetener",
"arugula",
"asadero",
"asafetida",
"asiago cheese",
"asparagus",
"aspic",
"avocados",
"azuki beans",
"baba",
"baba ghanoush",
"babaco",
"babka",
"baby kiwi",
"bacon",
"bacon grease",
"bagels",
"bagna cauda",
"bagoong",
"baguette",
"baharat",
"baking powder",
"baking soda",
"baklava",
"balsamic vinegar",
"bamboo shoots",
"bananas",
"bangers",
"bannocks",
"banon cheese",
"barbecue sauce",
"barberries",
"barley",
"barley sugar",
"basil",
"Basket Cheese",
"basmati rice",
"bass",
"bay leaves",
"beans",
"bean sauce",
"bean sprouts",
"bean threads",
"bechamel",
"beef",
"Beef Round Cuts",
"beer",
"beer cheese",
"beer sticks",
"beets",
"bel paese",
"berbere",
"berries",
"beurre blanc",
"beurre manie",
"biltong",
"biscuit mix",
"bisque",
"bitter melon",
"black beans",
"black kale",
"black olives",
"black-eyed peas",
"blackberries",
"blue cheese",
"blueberries",
"boerewors",
"bok choy",
"Bombay duck",
"Bon Appetit seasoning",
"borage",
"borscht",
"bottarga",
"bouillon",
"bouquet garni",
"bourbon",
"boursin cheese",
"brandy",
"brazil nuts",
"breadcrumbs",
"breadfruit",
"bresaola",
"brewer's yeast",
"brick cheese",
"broccoli",
"broccoli raab",
"broth",
"brown rice",
"brown sugar",
"brunoise",
"bruschetta",
"Brussels sprouts",
"buckwheat",
"buckwheat groats",
"bulgur wheat",
"butter",
"buttermilk",
"Buxton blue cheese",
"cabbage",
"cacao",
"cachaca",
"Caerphilly",
"calabaza",
"callaloo",
"Calvados",
"Canadian bacon",
"cannellini beans",
"canola oil",
"cantaloupes",
"cape gooseberries",
"capers",
"Cappuccino Latte",
"carambola",
"caraway seeds",
"cardamom",
"carob",
"carrageen",
"carrots",
"cashew nut",
"cassava",
"catfish",
"caul",
"cauliflower",
"caviar",
"cayenne pepper",
"celeriac",
"celery",
"celery seeds",
"chai",
"chambord",
"chard",
"chaurice sausage",
"chayote",
"cheddar cheese",
"cheese",
"cherimoya",
"cherries",
"chervil",
"Cheshire cheese",
"chestnuts",
"chickens",
"chicken livers",
"chickpeas",
"chicory",
"chile peppers",
"chili powder",
"chili sauce",
"Chinese Cabbage",
"Chinese dates",
"chipotle peppers",
"chives",
"chocolate",
"chowder",
"chutney",
"cider",
"cider vinegar",
"cilantro",
"cinnamon",
"citron",
"Citrus oils",
"clafouti",
"clams",
"clarified butter",
"cloves",
"cocoa powder",
"coconuts",
"coconut milk or cream",
"coconut oil",
"cod",
"coffee",
"colby",
"confit",
"cookies",
"cooking wine",
"Cool Whip",
"Copha",
"coriander",
"corn",
"corn flour",
"corn syrup",
"corned beef",
"cornichons",
"Cornish Yarg cheese",
"cornmeal",
"cornstarch",
"cottage cheese",
"cottage roll",
"coulis",
"couscous",
"crabs",
"craisins",
"cranberries",
"cranberry bean",
"crayfish",
"cream cheese",
"cream of coconut",
"cream of tartar",
"cream of wheat",
"crema de leche",
"creme de cacao",
"creme de cassis",
"creme de menthe",
"creme fraiche",
"cremini mushrooms",
"Creole sausage",
"crostini",
"croutons",
"crystallized ginger",
"cucumbers",
"cucuzza",
"cumin",
"curacao",
"currants",
"curry leaves",
"curry paste",
"curry powder",
"custard",
"dates",
"Date Paste",
"date sugar",
"demi-glace",
"Derby cheese",
"dhania-jeera powder",
"dill",
"Dovedale cheese",
"dragees",
"dried leeks",
"dripping",
"duck",
"dumpling",
"durian",
"eclairs",
"edam",
"edamame",
"eels",
"eggs",
"egg substitutes",
"eggplants",
"Elderberries",
"endive",
"English muffins",
"English mustard",
"epazote",
"erythritol",
"falafel",
"Falernum",
"farina",
"farmer cheese",
"fava beans",
"feet",
"feijoa",
"fennel",
"fennel seeds",
"fenugreek",
"fermented black beans",
"feta cheese",
"figs",
"file powder",
"finnan haddie",
"fish sauce",
"five-spice powder",
"flageolet",
"flax seed",
"flounder",
"flour",
"focaccia",
"foie gras",
"fond",
"Fontina Cheese",
"forcemeat",
"frangipane",
"french fries",
"French-style green beans",
"fried rice seasoning",
"frisee",
"galangal",
"ganache",
"garlic",
"garlic powder",
"gelatin",
"gelatinized starch",
"ghee",
"ginger",
"ginger ale",
"ginger beer",
"ginger syrup",
"ginkgo nut",
"glace de viande",
"Gloucester",
"Goji berry",
"golden syrup",
"gooseberries",
"gorgonzola",
"gouda",
"graham crackers",
"grains of paradise",
"gram flour",
"Grand Marnier",
"granola",
"grapes",
"grapefruits",
"grating cheese",
"great northern beans",
"green beans",
"green kern",
"green onions",
"greens",
"grits",
"grouper",
"Gruyere",
"guanbana",
"guavas",
"gumbo",
"habanero chilies",
"haddock",
"half-and-half",
"halibut",
"ham",
"ham hock",
"hamburger",
"hard cheese",
"Harissa",
"hash browns",
"Havarti",
"Hawaij",
"hazelnuts",
"hearts of palm",
"heavy cream",
"herbs",
"herbsaint",
"herring",
"Hispanic cheese",
"hoisin sauce",
"hoja santa",
"hoki",
"hominy",
"honey",
"honeydew melons",
"horseradish",
"hot sauce",
"huckleberries",
"Hungarian wax chile",
"hyssop",
"ice cream",
"ice wine",
"icing sugar",
"Indian pudding",
"instant espresso",
"instant potato flakes",
"invert sugar",
"Irish coffee",
"Irish cream liqueur",
"Irish mist",
"isinglass",
"jack cheese",
"jaggery",
"jambalaya",
"jamon serrano",
"jamun",
"jelly beans",
"jelly tots",
"Jerusalem artichokes",
"jicama",
"jowl",
"Kabsa Spice Mix",
"kaffir lime",
"Kahlua",
"kalamata olives",
"kale",
"kamaboko",
"kasha",
"kashk",
"ketchup",
"ketjap manis",
"kewra essence",
"kewra water",
"Khus Essence",
"kidney beans",
"kielbasa",
"kirsch",
"Kitchen Bouquet",
"kiwi fruit",
"kohlrabi",
"konfyt",
"kudzu",
"kugel",
"kumquats",
"ladyfingers",
"lamb",
"Lambsquarters",
"Lampreys",
"Lancashire cheese",
"lardons",
"lavender",
"leeks",
"Lefse",
"lemons",
"lemon balm",
"lemon grass",
"lemon juice",
"Lemon Peel",
"lentils",
"lettuce",
"Li Hing Mui",
"light cream",
"lima beans",
"limes",
"lingcod",
"litchi",
"liver",
"lobsters",
"longans",
"loquat",
"lotus",
"lovage",
"lumpia wrappers",
"macadamia nut butter",
"macaroni",
"mace",
"mackerel",
"Madeira",
"mahi mahi",
"mahleb",
"malt vinegar",
"Mandarin oranges",
"mangoes",
"mangosteen",
"manzanilla olives",
"maple syrup",
"maraschino cherries",
"margarine",
"marjoram",
"marmalade",
"Marsala",
"marshmallows",
"marula",
"marzipan",
"masa harina",
"masala",
"masarepa",
"mascarpone",
"matignon",
"matzo meal",
"mayonnaise",
"melons",
"meringue powder",
"mesclun",
"mettwursts",
"milk",
"mimolette cheese",
"Mini Babybel Light",
"mint",
"Miracle Whip dressing",
"mirepoix",
"miso",
"mixed spice",
"mizuna",
"Moambé Sauce",
"molasses",
"monkfish",
"moo shu wrappers",
"morels",
"Moreton Bay Bug",
"moringa",
"mortadella",
"mostaccioli",
"mozzarella",
"mugwort",
"mung beans",
"Muscadine grape",
"muscovado sugar",
"Muscovy duck",
"mushrooms",
"muskmelons",
"mussels",
"mustard, prepared",
"mustard, seed and powder",
"nasturtium",
"navy beans",
"nectarines",
"nigella seeds",
"nopales",
"nori",
"O'Brien potatoes",
"oatmeal",
"octopus",
"okra",
"olives",
"olive oil",
"onions",
"onion powder",
"oranges",
"orange flower water",
"Orange Peel",
"oregano",
"orgeat syrup",
"oyster sauce",
"Palm oil",
"palm sugar",
"pancetta",
"panir",
"panko",
"panna cotta",
"papayas",
"paprika",
"parchment paper",
"Parmesan cheese",
"parsley",
"parsnips",
"passion fruit",
"pasta",
"pasta filata cheese",
"pastis",
"peas",
"pea beans",
"peaches",
"peanuts",
"peanut butter",
"pears",
"pecans",
"Pelargonium citronellum",
"Peppadew peppers",
"pepper",
"perch",
"Periwinkles",
"persimmons",
"pesto",
"pheasants",
"phyllo dough",
"pickles",
"pickling lime",
"pico de gallo",
"pie melon",
"pierogies",
"pig's cheek",
"pig's feet",
"pike",
"piloncillo",
"pimiento",
"pine nuts",
"pineapples",
"pink beans",
"pinto beans",
"pistachios",
"plantains",
"plums",
"plum tomatoes",
"plumcots",
"polenta",
"pomegranates",
"pomegranate molasses",
"pomelos",
"Pomona's Universal Pectin",
"pompano",
"ponzu",
"poppy seeds",
"porcini",
"pork",
"portabellas",
"potatoes",
"potato chips",
"potato starch",
"poultry seasoning",
"poussin",
"powdered sugar",
"prawns",
"preheat",
"preserves",
"preserved lemon",
"processed cheese",
"proof",
"Prosciuttini",
"prosciutto",
"provel rope cheese",
"provolone",
"prunes",
"pudding mixes",
"puff pastries",
"pulses",
"pumpkins",
"pumpkin pie spice",
"Pumpkin seeds",
"purslane",
"quail",
"quark",
"quenelles",
"quesadilla",
"queso",
"quetsch",
"quince",
"quinoa",
"quorn",
"rabbits",
"radiatore",
"radicchio",
"radishes",
"raisins",
"rambutan",
"ramps",
"ras el hanout",
"raspberries",
"raw sugar",
"Recado rojo",
"recaito",
"red beans",
"red cabbage",
"red chile powder",
"Red Leicester",
"red pepper flakes",
"red snapper",
"remoulade",
"rhubarb",
"rice",
"rice paddy herb",
"rice paper",
"rice sticks",
"rice vermicelli",
"rice vinegar",
"rice wines",
"ricotta cheese",
"romaine lettuce",
"Romano cheese",
"Rookworst",
"rose essense",
"rose water",
"rosemary",
"Rotel tomatoes",
"rotisserie",
"roux",
"rum",
"rusks",
"",
"saffron",
"sage",
"sago",
"salmon",
"salsa",
"salsify",
"salt",
"salt pork",
"sambal",
"Sand Dab",
"sandwich",
"sardines",
"satay",
"sauerkraut",
"Saunf",
"sausages",
"saute",
"savory",
"sazon",
"scald",
"scallops",
"scaloppine",
"Scotch bonnet chiles",
"Scoville Chart",
"scrapple",
"screwpine leaves",
"sea cucumbers",
"sear",
"seed",
"seitan",
"semi-hard cheese",
"semisweet chocolate",
"semolina",
"sesame seeds",
"seville orange",
"shallots",
"sherry",
"shitakes",
"shortening",
"shrimp",
"shrimp paste",
"Shropshire Blue",
"simmer",
"Slipper Lobster",
"smelt",
"smoke seasoning",
"smoked salmon",
"snap peas",
"snapper",
"snoek",
"snow peas",
"soba",
"soba tsuyu",
"soda crackers",
"sodium citrate",
"soft cheese",
"soft-shell crabs",
"sole",
"somen",
"sorghum",
"sorrel",
"souffle",
"sour cream",
"soy sauce",
"soybeans",
"soymilk",
"spaetzle",
"spaghetti squash",
"Spanish cheeses",
"spatchcock",
"spearmint",
"specialty cheeses",
"spinach",
"split peas",
"squash",
"squid",
"star anise",
"steaks",
"steam",
"stevia",
"Stilton",
"strawberries",
"stuffings",
"sturgeon",
"sucanat",
"succotash",
"suet",
"sugar",
"sultana",
"sumac",
"summer squash",
"sunflower seeds",
"sushi",
"sweet chili sauce",
"sweet peppers",
"sweet potatoes",
"sweetbreads",
"sweetened condensed milk",
"swiss cheese",
"swordfish",
"Szechuan peppercorn",
"Tabasco sauce",
"tagine",
"tahini",
"tamarillo",
"tamarind",
"tandoori paste",
"tapioca",
"tarragon",
"tartar sauce",
"tasso",
"tatsoi",
"tea",
"teff",
"tempeh",
"terrapins",
"thyme",
"tofu",
"togarashi",
"tomatoes",
"tomato juice",
"tomato paste",
"tomato puree",
"tomato sauce",
"tonic water",
"tortillas",
"trappist or monastery-style cheese",
"tripe",
"trompette de la mort mushroom",
"trout",
"truffles",
"tuna",
"turbinado sugar",
"turkeys",
"Turkey kielbasa",
"turmeric",
"turnips",
"udo",
"udon noodles",
"ugli fruit",
"umeboshi",
"unsweetened chocolate",
"urad dal",
"vanilla",
"vanilla bean",
"veal",
"vegan brand names",
"vegemite",
"vegetable marrow",
"vegetarian brand names",
"veloute",
"Velveeta",
"venison",
"vermouth",
"vidalia onions",
"vincotto",
"vinegar",
"vital wheat gluten",
"wakame seaweed salad",
"walnuts",
"wasabi",
"washed-rind cheese",
"water",
"water bath",
"water chestnuts",
"waterblommetji",
"watercress",
"watermelons",
"watermelon radishes",
"wattleseed",
"Weetabix",
"weisswurst",
"Welsh rarebit",
"Wensleydale cheese",
"wheat berries",
"wheat germ",
"whelks",
"white beans",
"white chocolate",
"wild rice",
"wine",
"wine vinegar",
"won ton skins",
"woodruff",
"Worcestershire sauce",
"yabbies",
"yeast",
"yogurt",
"yukon gold potatoes",
"yuzu kosho",
"za'atar",
"zabaglione",
"zest",
"zinfandel wine"
]

ingredients_list.each do |name|
  Ingredient.create(name: name)
end
